### ISSUE TITLE
Feature requests are welcome!

### ISSUE THREAD

**Issue by Enase** [haftahave/serverless-ses-template#18]
Hi there!

Any proposals or feature requests are welcome here.
Feel free to leave comments or discuss any ideas.

Thanks in advance.

**Comment by stgogm** [comment]
Thank you for this! The only recommendation I would like make is the custom config to be an object, like most other plugins do:

```yaml
custom:
  sesTemplates:
    disableAutoDeploy: true
    addStageAlias: true
    configFile: './custom-config-file/path.js'
    region: 'us-west-2'
```
